services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "flight-booking-system"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5435:5432"