spring:
  mvc:
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5435/flight-booking-system
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  messages:
    fallback-to-system-locale: false